---
- name: Down docker compose for Metube
  community.docker.docker_compose_v2:
    project_src: "{{ metube_node_docker_compose_app }}"
    state: absent
    files:
      - docker-compose.yml
  register: __output_metube_down

- name: Show results down
  ansible.builtin.debug:
    var: __output_metube_down

- name: Delete metube dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - { path: "{{ metube_node_docker_compose_app }}" }
    - { path: "{{ metube_node }}" }
