---
- name: Down docker compose for Torrserver
  community.docker.docker_compose_v2:
    project_src: "{{ torrserver_node_docker_compose_app }}"
    state: absent
    files:
      - docker-compose.yml
  register: __output_torrserver_down

- name: Show results down
  ansible.builtin.debug:
    var: __output_torrserver_down

- name: Delete Torrserver dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - { path: "{{ torrserver_node_docker_compose_app }}" }
    - { path: "{{ torrserver_node }}" }
